#!/bin/bash

build() {
    add_binary grep
    add_binary blkid

    add_runscript

}

help() {
    cat <<HELPEOF
This hook initializes a USB-secret methode the system start of the Stick
The System start not the Stick.
HELPEOF

}

# vim: set ft=sh ts=4 sw=4 et:
